### ISSUE TITLE
ForceNullable on Class/Interface Level

### ISSUE THREAD

**Issue by schwamster** [reinforced/Reinforced.Typings#14]
I would like to use the ForceNullable Attribute on Class/Interface Level so that all Properties of the Class/Interface are optional in the resulting ts.

=>
Forces all properties to be nullable. E.g. field:boolean becomes field?:boolean when you specify [TsInterface(ForceNullable = true)] in attribute configuration

Is that something that could be interesting to others?

**Comment by pavel-b-novikov** [comment]
You can do almost the same thing using fluent configuration already - so you can specify 

```cs
.With*Properties(c=>c.ForceNullable());
```

I'm not sure that it is necessary to add it to attributes configuration because it may be confusing when you have already specified ForceNullable for all the properties and then you suddenly decided to make one/two/three properties not nullable. Now it is much more flexible to use fluent configuration for that, but if someone else is interested then I can implement.

**Comment by schwamster** [comment]
thanks for that snippet. I have to admit i did not check out the fluent configuration yet. 
works great and this suits me much better than attribute configuration anyways.

**Comment by pavel-b-novikov** [comment]
Find out more here: https://github.com/reinforced/Reinforced.Typings/wiki
