### ISSUE TITLE
WithPublicProperties exports static properties

### ISSUE THREAD

**Issue by Daniel15** [reinforced/Reinforced.Typings#142]
Class:
```csharp
public class MyClass
{
	public static string StaticFoo { get; set; }
	public string InstanceFoo { get; set; }
}
```

Config:
```csharp
builder.ExportAsInterface<MyClass>()
	.WithPublicProperties();
```

Can result in:
```ts
export interface IMyClass
{
	instanceFoo: string;
	staticFoo: string;
}
```

Is it expected behaviour? This seems a bit weird as usually serialization does **not** include static properties.

If this is not expected, I can submit a PR to add a `WithPublicInstanceProperties` if you don't want to modify existing behaviour (since other people could be relying on it).

I'm doing this instead, which works fine:
```csharp
builder.ExportAsInterface<MyClass>()
	.WithProperties(BindingFlags.Instance | BindingFlags.Public);
```

**Comment by resolritter** [comment]
FWIW TS does have both static/member getters and setters, so conversion can be direct.

[link](http://www.typescriptlang.org/play/?ssl=6&ssc=6&pln=4&pc=1#code/MYGwhgzhAEAqAWYAuBhcVoG8BQ0-QAcAnASwDdkBTaAfQpAFdKAuaCJUgOwHNoBeaACJB2XPnbISwaN0pI4ACgCUWMfnxE5DIpyGwR6gL6j1s+fSbLV69ZqTbdSeCQgA6OmEaU10Yz4hy0BaUCsGs7FzcKjg2+E4u7sH8QZ5MPsZ+nJQA7nCIqOgQyq5JAoIAjCKiQA)

As per
> This seems a bit weird as usually serialization does not include static properties.

I personally expect more along the lines of code translation, rather than serialization, from this library.

**Comment by pavel-b-novikov** [comment]
> code translation, rather than serialization

👍 

@Daniel15 Look. I cannot predict what behavior people exectly need. So I have left extension points for that. Is fine if you have made your static method to achieve behavior that you'd like, but it is not the reason to inclue it into library, I think. This way eventually we will have dozens of particular methods per each corner-case. I think it does not sound like correct library evolution process. I'm trying to implement concepts required in issues rather than corner-cases.

**Comment by Daniel15** [comment]
Sure, that makes sense. Thanks for the reply!
