### ISSUE TITLE
GenerateDocumentation not working in library project

### ISSUE THREAD

**Issue by Xenoage** [reinforced/Reinforced.Typings#158]
When I use the `GenerateDocumentation` feature in a (.NET Standard 2.1) library project, the XMLDOC file is not found automatically. I could fix it by configuring the path like this:

`builder.TryLookupDocumentationForAssembly(Assembly.GetCallingAssembly(),
                Directory.GetCurrentDirectory() + "../../(ProjectName)/(AssemblyName).xml");`

I'm not sure if the problem is that the TS compiler regards the wrong project (the main project instead of the library project?) or if the path is wrong. Using `Assembly.GetCallingAssembly()` and a directory relative to `Directory.GetCurrentDirectory()` did the trick for me.

Maybe this should work automatically.

**Comment by pavel-b-novikov** [comment]
Well, in fact things are bit more complicated. XMLDOC path may differ (since it is configurable in project properties), so therefore RT retrieves it from corresponding MSBuild variable. And I actually cannot guarantee that behavior of fullfilling this variable will stay the same across further .NET versions. That is why `TryLookupDocumentationForAssembly` exists. So the solution that looks straightforward is not-so-straightforward. I'm afraid that for now I cannot make it automatical.

**Comment by Xenoage** [comment]
Thanks for having a look at it. Works fine for me using the above workaround, maybe this issue is helpful for other users.
