### ISSUE TITLE
"type" keyword for ts imports

### ISSUE THREAD

**Issue by JoschaHemlep** [reinforced/Reinforced.Typings#216]
I'm currently working on a svelte project and would love to use RT and RtDivideTypesAmongFiles=true, 
but svelte needs "import **type** { FOO } from './FOO';" for type imports and i couldn't find a way to specify the "type" keyword for the generated TS code.
Is there already a way to achieve this?

**Comment by pavel-b-novikov** [comment]
Reinforced.Typings is pretty flexible and supports lots of workarounds. Like this one.

1. Inherit [`TypeScriptExportVisitor`](https://github.com/reinforced/Reinforced.Typings/tree/master/Reinforced.Typings/Visitors/TypeScript)
2. Override the overload of method [`Visit`](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings/Visitors/TypeScript/TypeScriptExportVisitor.Dependencies.cs) for `RtImport` parameter
3. Implement the `import type` handling logic in way that you want. Most likely you will have to re-implement `Visit` for `RtImport` completely, but it is about 20 lines of code.
4. Call method [`UseVisitor<T>`](https://github.com/reinforced/Reinforced.Typings/blob/2fee1e693af58f2d25cbc7e3e07c25c95a5e06f6/Reinforced.Typings/Fluent/GlobalConfigurationBuilder.cs#L180) on global configuration fluent builder to inject your inherited visitor for this purpose.

To debug your changes you may use [what is done for RT's unit testing](https://github.com/reinforced/Reinforced.Typings/blob/2fee1e693af58f2d25cbc7e3e07c25c95a5e06f6/Reinforced.Typings.Tests/ConfigurationBuilderTestBase.cs#L13). This setup helps to run whole generation pipeline outside of build process. Also check out what [happens when test asserts](https://github.com/reinforced/Reinforced.Typings/blob/2fee1e693af58f2d25cbc7e3e07c25c95a5e06f6/Reinforced.Typings.Tests/Core/RtExporterTestBase.cs#L11). 

It will help you to develop your own setup that fits your needs perfectly.
