### ISSUE TITLE
Reinforced.Typings : Unexpected error RT0999: An item with the same key has already been added.

### ISSUE THREAD

**Issue by alexdresko** [reinforced/Reinforced.Typings#28]
Started getting this error last week after I made a lot of changes to my project. Not sure where to begin looking to fix the problem, but thought I might get a head start on tomorrow if I go ahead and post here. 

Anything I can do to help debug this situation?

**Comment by pavel-b-novikov** [comment]
Can you contact me via skype/teamviewer? I need to know at least stack trace

**Comment by pavel-b-novikov** [comment]
It would be also nice if you:

1) Add MsBuild to your %PATH% env. variable (usually located at ```%SYSTEMDRIVE%\Program Files (x86)\MSBuild\_version_\Bin\```)
2) Open cmd and go to your project's dir
3) Made some changes to one of your .cs files
4) run ```msbuild.exe /v:d _YourProjectName.csproj_ > buildlog.txt```
5) Post this file to gist, or send to me somehow

**Comment by alexdresko** [comment]
Thanks for the quick reply! I've narrowed the problem down to a small set of code changes I made, so I'm thinking I'll figure it out soon. If not, I'll happily proceed with your instructions.

**Comment by pavel-b-novikov** [comment]
Have a good time!

**Comment by alexdresko** [comment]
The problem occurs when I add the `Microsoft.AspNet.Odata` nuget package to my project. I haven't had time to reproduce the problem in a brand new project. In the meantime, do you have any ideas why that nuget package (and all of it's supporting packages) would cause problems?

**Comment by pavel-b-novikov** [comment]
Well, there may be things caused by statis initialization (somewhere in Microsoft.AspNet.Odata there are classes with tricky static constructors that you access inside Configure method), or you are using some classes from mentioned package as fields for your exported classes (it happens from time to time, e.g. I have had similar error when exported JS ViewModels containig JRaw fields from Newtonsoft.Json: JRaw is implementing IEnumerable, so RT hanged trying to understand its type). 
Complete answer you can get from buildlog.txt mentioned above. It will contain stack trace and maybe it will help (search buildlog.txt by "rtcli" keyword).

**Comment by pavel-b-novikov** [comment]
When problem will be solved - please close issue by yourself

**Comment by alexdresko** [comment]
Just FYI. I never figured this out. Ended up switching to Typewriter.
