### ISSUE TITLE
1.3.7 no longer forces nullable (typescript optional) on nullable types

### ISSUE THREAD

**Issue by PandaWood** [reinforced/Reinforced.Typings#49]
I just wanted to check that this is deliberate
On updating to 1.3.7 from 1.3.0 I found that this C# field, decorated with attribute [TsClass] now creates a typescript field that isn't optional

```public int? StartPageID { get; set; }```

TypeScript output:
```
    public startPageID?: number;  // 1.3.0
    public startPageID: number;   // 1.3.7
```

Admittedly, I wanted to use TsInterface for this but my team mate has forced me to use TsClass for some reason

**Comment by pavel-b-novikov** [comment]
Hm... I will doublecheck unit tests

**Comment by pavel-b-novikov** [comment]
Probably your problem was about using ```TsProperty``` along with fluent configuration - they have had some conflicts.

Please update to 1.4.1 version - it is fixed there.

[unit test for you](https://github.com/reinforced/Reinforced.Typings/blob/master/Reinforced.Typings.Tests/SpecificCases/SpecificTestCases.TsPropertyWorks.cs)
