### ISSUE TITLE
 MSB4044: The "RemoveTypeScriptStep" task was not given a value for the required parameter "Original".

### ISSUE THREAD

**Issue by PandaWood** [reinforced/Reinforced.Typings#50]
The only thing I've changed in my codebase, to get this error, is to move my **tsconfig.json**
Which technically, has nothing to do with Reinforced.Typings, since it doesn't build my typescript or need to know anything about it. 

So maybe this is an issue to request that if `RtBypassTypeScriptCompilation=true`, then cater for not finding or having anything to do with my tsconfig.json file?

```
Reinforced.Typings.settings.xml : warning : TypeScript sources will not be built before project compile because it is disabled by Reinforced.Typings configuration [C: \code\src\Web.Site\Web.Site.csproj]
RT is fixing build tasks
RT has fixed build tasks:ResolveReferences;ResolveKeySource;SetWin32ManifestProperties;_GenerateCompileInputs;BeforeCompile;_TimeStampBeforeCompile;CoreCompile;_TimeStampAfterCompile;AfterCompile;;_AfterCompileWinFXInternal
C:\code\packages\Reinforced.Typings.1.3.0\build\Reinforced.Typings.targets(58,3): error MSB4044: The "RemoveTypeScriptStep" task was not given a value for the
required parameter "Original". [C:\code\src\Web.Site\Web.Site.csproj]
```

**Comment by pavel-b-novikov** [comment]
I have dirty hack to suggest :D

Add to your Reinforced.Typings.settings.xml, at early beginning, right after opening ```<PropertyGroup>``` tag, the following lines:

```xml
<PublishPipelineCollectFilesCore>Stub</PublishPipelineCollectFilesCore>
<BuiltProjectOutputGroupDependsOn>Stub</BuiltProjectOutputGroupDependsOn>
```

Check if it is working correctly. If no - remove 2nd line

**Comment by PandaWood** [comment]
Thanks, yes this works for now. I left just the first line in

**Comment by masteroleary** [comment]
@pavel-b-novikov 
While your solution temporarily fixed the immediate issue and allowed dotnet watch to compile, it also made visual studio 2017 unable to find any nuget references (as in ALL include system and aspnet.mvc)

I wasn't aware that this was causing it and spent two days dealing with nuget restore, changing the location of the user nuget packages, forcing it to not use global nuget packages, etc. Finally I recreate my branch one change at a time until i found that applying your change and then closing and opening VS caused the issue. Just wanted to put this here and hopefully safe another developer some hair.

Because I believed it was "working" and did remove the MSB4044 error I did not follow your next step, which was to remove the 2nd line. After doing so, all the nuget references and intellisense was restored.
